version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.app
      - FLASK_ENV=development
      - FLASK_DEBUG=1 
    volumes:
      - .:/app
    networks:
      - nginx-certbot-network

networks:
  nginx-certbot-network:
    external:
      name: nginx-certbot-network